### ISSUE TITLE
Errors in Job Session Log after adding new empty external reference

### ISSUE THREAD

**Issue by DmitriyYukhanov** [RockTomate/Issues#1]
**Steps to Reproduce**
* open Variables view
* switch to external tab
* press + button
* see errors in Job Session Log

**Expected Results**
no errors in log

**Actual Results**
errors in Job Session Log
![image](https://user-images.githubusercontent.com/883587/78674486-5ad8e400-78ec-11ea-944d-01d124fccbc4.png)

**Comment by DmitriyYukhanov** [comment]
Errors stop appearing when I assign Variables bank to the external reference field.

**Comment by ElmarTalibzade** [comment]
Fixed in 1.0.2
