### ISSUE TITLE
Variable bank does not save when you finish editing variables

### ISSUE THREAD

**Issue by DmitriyYukhanov** [RockTomate/Issues#12]
**Steps to Reproduce**
* create new variables bank
* commit changes in VCS
* edit variables in bank and close bank editor
* see no new changes in VCS
* save project from File>Save Project
* see changes are visible in VCS now

**Expected Results**
I expect bank editor to save changes when I close editor or even when I unfocus input field

**Actual Results**
Bank editor does not saves changes immediately leading to possible data loss if Unity will crash before you'll save project changes.

**Comment by ElmarTalibzade** [comment]
Fixed in 1.0.3
