### ISSUE TITLE
Getting exceptions spam in console from Job Session Log window after project reopen

### ISSUE THREAD

**Issue by DmitriyYukhanov** [RockTomate/Issues#13]
**Steps to Reproduce**
Unfortunately I'm not sure how to reproduce it.
I did tried to reproduce it when I faced this problem first time but had no luck.
Now I see it again and not sure what's exactly leads to this problem.

Simply I run few jobs, while Job Session Log window is visible, close project, reopen it again and sometimes it's totally fine but sometimes it throws errors in console and Job Session Log window stays empty

**Expected Results**
No errors in console.

**Actual Results**
Errors spam in console:

`ArgumentException: Invalid Depth info in input list. Depth cannot increase more than 1 per row. Index 0 has Depth -1 while index 1 has Depth 2
HardCodeLab.RockTomate.Editor.Helpers.TreeElementUtility.ValidateDepthValues[T] (System.Collections.Generic.IList`1[T] list) (at Library/PackageCache/com.modumlab.thirdparty.tools.rocktomate@1.0.0/RockTomate/Scripts/Editor/Helpers/TreeElementUtility.cs:122)
HardCodeLab.RockTomate.Editor.Helpers.TreeElementUtility.ListToTree[T] (System.Collections.Generic.IList`1[T] list) (at Library/PackageCache/com.modumlab.thirdparty.tools.rocktomate@1.0.0/RockTomate/Scripts/Editor/Helpers/TreeElementUtility.cs:43)
HardCodeLab.RockTomate.Editor.Controls.TreeModel`1[T].Init (System.Collections.Generic.IList`1[T] data) (at Library/PackageCache/com.modumlab.thirdparty.tools.rocktomate@1.0.0/RockTomate/Scripts/Editor/Controls/TreeViews/TreeModel.cs:44)
HardCodeLab.RockTomate.Editor.Controls.TreeModel`1[T].SetData (System.Collections.Generic.IList`1[T] data) (at Library/PackageCache/com.modumlab.thirdparty.tools.rocktomate@1.0.0/RockTomate/Scripts/Editor/Controls/TreeViews/TreeModel.cs:34)
HardCodeLab.RockTomate.Editor.Controls.TreeModel`1[T]..ctor (System.Collections.Generic.IList`1[T] data) (at Library/PackageCache/com.modumlab.thirdparty.tools.rocktomate@1.0.0/RockTomate/Scripts/Editor/Controls/TreeViews/TreeModel.cs:24)
HardCodeLab.RockTomate.Editor.Windows.JobSessionLogWindow.Init () (at Library/PackageCache/com.modumlab.thirdparty.tools.rocktomate@1.0.0/RockTomate/Scripts/Editor/Windows/JobSessionLogWindow.cs:65)
HardCodeLab.RockTomate.Editor.Windows.JobSessionLogWindow.OnGUI () (at Library/PackageCache/com.modumlab.thirdparty.tools.rocktomate@1.0.0/RockTomate/Scripts/Editor/Windows/JobSessionLogWindow.cs:191)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <92f998fbb4ca4d8dab7793d6e003b794>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <92f998fbb4ca4d8dab7793d6e003b794>:0)
UnityEditor.DockArea.OldOnGUI () (at <92f998fbb4ca4d8dab7793d6e003b794>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <e40488dcb2e3475fad9ef37a4468eea0>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
`

**Comment by DmitriyYukhanov** [comment]
Executing job does fixes this (job logs become visible as well)

**Comment by ElmarTalibzade** [comment]
I am going to address this in the future update.

**Comment by ElmarTalibzade** [comment]
Fixed in 1.0.3
