### ISSUE TITLE
[Duplicating a Job and using it as a RunJob triggers an error]

### ISSUE THREAD

**Issue by amartinez1660** [RockTomate/Issues#14]
**Reason for the usage**
Sometimes it’s nice to ‘refactor’ a group of steps that are inside a job as a separate standalone job on it’s own. (I.e. a series of Create, Copy, Move Folders that could be re-used by many jobs).
This can be currently achieved by duplicating a job and deleting all the steps that were not part of the intended ‘refactor’

**Steps to Reproduce**
* Duplicate a JobA inside unity’s Project Browser section (let’s call it JobB)
* Open JobB and remove steps not needed for this “refactor”
* Open JobA back, remove the steps that are meant to be replaced by JobB
* Create a RunJob (pointing to JobB)

**Expected Results**
Runs JobB

**Actual Results**
Several things can happen:
* JobB cannot be assigned on the reference slot of JobA’s RunJob step (the intended reference type the slot expected sometimes switches to a variables object type instead of a Jobs object type)
* Closing and opening unity will fix the previous reference type bug, but assigning JobB to RunJob of JobA and running it will fail (it outputs an error on the log that says that it cannot Run the ‘same’ job it’s currently run... might be a serialization error during file duplication)

**Comment by ElmarTalibzade** [comment]
Fixed in 1.0.3
