### ISSUE TITLE
[RunJob - Maybe not a Bug] The External Variables have to be referenced on the parent that executes RunJob. 

### ISSUE THREAD

**Issue by amartinez1660** [RockTomate/Issues#17]
**Steps to Reproduce**
* Create a **Job (JobChild)** that uses an Externals Variables Asset.
* Create Job Parent which at some point calls RunJob(**JobChild**), no externals variables assigned.

**Expected Results**
**JobParent** manages to run **JobChild**.

**Actual Results**
Externals variables used in **JobChild** won't resolve (will stay _%variablename%_);
Temporal Fix: Add the same **External variables** asset used by **JobChild** in **JobParent**.
This is maybe by design (as that would allow for overrides), however, it would be nice that if we don't add the same variables anywhere, that **JobParent** could run **JobChild** without having to know too much about the variables on **JobChild**

**Comment by ElmarTalibzade** [comment]
Normally, you'd have to explicitly specify what variables to pass to a child Job. External variables are not detected during the setup, which is why they are never detected in the first place.

I agree the current system is not great, so I will add this to the backlog to address this issue.

**Comment by ElmarTalibzade** [comment]
Fixed in 1.0.3
