### ISSUE TITLE
[Root Vars] Application version and Build Number

### ISSUE THREAD

**Issue by amartinez1660** [RockTomate/Issues#19]
**Feature Proposal**
Application Version and Build number on the root variable set (maybe there's a better way).
Build number might need to be dynamic in the sense that it depends on the player's settings per platform.

**Problem this Solves**
When creating build target paths it would be nice to be able to get the Application.version and build number from the app.

**Extra notes**
Can we add variables to that root vars window list?

**Comment by ElmarTalibzade** [comment]
`Application.version` will now be available in the next update as `%AppVersion%`

As for build number, I would need to consider the plan of action. You could have a text file that contains the build number, read it, increment it, and then write back to the text file.

**Comment by amartinez1660** [comment]
Awesome.
Yeah it's not consistent between platforms either... on Android it's called Bundles (and can't be 0), on Mac and iOS it is indeed build number.
Currently I'm just basing all of them on the iOS one only. Probably something more specific per project to tackle and not a full library, just created a macro for now that gets the platform's equivalent build number via current BuildTarget, if it doesn't have a build number it defaults to the iOS one.

The file approach it's a great idea as it could unify them all together for the platforms that don't handle it, the user can keep track of it on it's own.

**Comment by ElmarTalibzade** [comment]
Some additional work would be required to implement this feature.

While having variables that store versions would be pretty straight-forward, there still needs to be a way to store modified variables.

At the moment, the Job that gets executed gets cloned and that copy has its variables modified. This is done to avoid file corruption should anything occur.

In other words, changes to local variables won't be carried over.

**Comment by ElmarTalibzade** [comment]
Update 1.1.0 has introduced Persistent Variables. This will let you create an integer variable, mark it as "persistent" then increment it every time job runs and its value would be saved.

Read more: https://rocktomate-docs.onrender.com/variables/persistent-variables

Apologies for the late update!
