### ISSUE TITLE
Creating variables with spaces in names silently fails

### ISSUE THREAD

**Issue by DmitriyYukhanov** [RockTomate/Issues#2]
**Steps to Reproduce**
* try creating new variables with spaces in name
* see nothing happens - no errors and nothing else happens after you press "Create" button

**Expected Results**
I expect see some error if this action is not allowed.

**Actual Results**
Nothing happens.

**Comment by DmitriyYukhanov** [comment]
Same for dots in variables names.

**Comment by ElmarTalibzade** [comment]
Variable names with spaces are not allowed including other illegal characters. Give variable names that you'd give them when programming.

I would need to add some visual feedback on this.

**Comment by DmitriyYukhanov** [comment]
I see, yeah, some feedback would be appreciated here since it could be not obvious illegal chars are not allowed.

Thanks!

**Comment by ElmarTalibzade** [comment]
Implemented in 1.0.2
![image](https://user-images.githubusercontent.com/8478519/78769180-e3a35e80-7984-11ea-8873-f87230cf80c2.png)
