### ISSUE TITLE
[Blocker Bug] Clicking on External and creating a Var Bank breaks Run Job's TargetJob Field

### ISSUE THREAD

**Issue by amartinez1660** [RockTomate/Issues#21]
**Steps to Reproduce**
* Create a RockTomate automated Job
* Create a new Run Job step inside (Target Job field is correctly of type Job)
* Click on the External variable on the variables window, click on the 'create a new bank' + button.
* RunJob targetJob's field changes to type of Variable Bank and stays that way until Unity is restarted

**Environment**
Unity 2019.3.9f1 OSX
Unity 2019.3.9f1 Windows
This was a sneaky one to find, but these steps gets it triggered 100% on my side.

**Actual Results**
The target job's field changes from typeof 'Job' to typeof 'Variable Bank' with no way to get back to job type until unity is restarted

**More Info**
* If there was a variable bank already assigned to the automated job's variable config, just clicking on the External Variables tab will also trigger the bug, any RunJob without assigned Job's will have an incorrect target job field type
* Duplicating already properly configure 'RunJob' steps on the current work space to get around the issue won't work, the newly duplicated RunJob step has no job assigned to it and the field to Variable Bank type.

**Comment by ElmarTalibzade** [comment]
Fixed in 1.0.3
