### ISSUE TITLE
Modified on runtime VariableBanks aren't dirty, and cant be saved without edit.

### ISSUE THREAD

**Issue by BaalEvan** [RockTomate/Issues#25]
**Steps to Reproduce**
* Create Step which update Variable from VariableBank via Output
* Run Job
* You can see updated value in editor but, after save project asset file isn't updated

**Expected Results**
VariableBanks modified by Runtime should be saved during save project

**Actual Results**
VariableBanks are changed only in Library, and asset isn't dirty so can't be saved

**Comment by ElmarTalibzade** [comment]
I overlooked Variable Banks when I was implementing this feature. Thanks for bringing this up!

**Comment by ElmarTalibzade** [comment]
Bug fixed 🎉 Will be included in the next release.
