### ISSUE TITLE
Variable Bank List - Add Scroll

### ISSUE THREAD

**Issue by BaalEvan** [RockTomate/Issues#29]
**Feature Proposal**
Window launched from Variable Bank to preview List items should have Scroll

**Problem this Solves**
If you have list with 20+ elements (for example you are using 2 separate lists of Scenes to include in build not related to BuildWindow you cant preview all elements because there is no scroll

**Comment by ElmarTalibzade** [comment]
Never thought about this. Thanks for bringing this up!

**Comment by ElmarTalibzade** [comment]
Added a scroll when dealing with large lists. Will be introduced in the next update.

![image](https://user-images.githubusercontent.com/8478519/129979727-52177b73-f65a-4580-ae49-55f1ab5fb3f4.png)
