### ISSUE TITLE
Edit existing variables names and types

### ISSUE THREAD

**Issue by DmitriyYukhanov** [RockTomate/Issues#3]
**Feature Proposal**
Would be great to be able to edit existing variables names and types, even without applying those changes to the places where variables are used - it would already help a lot.

**Problem this Solves**
It would allow quickly fix incorrect name or type if you accidentally select \ input wrong values before creating variable.
Now you have to remove old variable and create new one from scratch which is pretty time-consuming when dealing with lots of variables.

**Comment by ElmarTalibzade** [comment]
You can already do that! When variable is selected, press F2.

But I do plan on being able to rename it through more obvious means like context menu or double-clicking it.

**Comment by DmitriyYukhanov** [comment]
Ah thank you, yes, context menu would be nice to have as well ^^
