### ISSUE TITLE
[Feature] Script Field for Steps (for easier access)

### ISSUE THREAD

**Issue by BaalEvan** [RockTomate/Issues#30]
**Feature Proposal**
I think scriptField reference like in classic Inspector is very useful if you want to edit step

**Problem this Solves**
Right now I have to look for script asset in projectWindow every time I want to edit stepScript or open script using VS, I would like to have easier access to script.

**Example**
![image](https://user-images.githubusercontent.com/1843494/131355274-4ffe20dd-120d-437e-a8e5-8cc13dfee271.png)

**Example Implementation**
```cs
    private void DrawStepHeader()
        {
            string[] assets = AssetDatabase.FindAssets(SelectedStep.GetType().Name);
            GUI.enabled = false;
            foreach (string assetGUIDS in assets)
            {
                string path = AssetDatabase.GUIDToAssetPath(assetGUIDS);
                Object script = AssetDatabase.LoadAssetAtPath(path, typeof(MonoScript));
                EditorGUILayout.ObjectField("Script", script, SelectedStep.GetType(), false);
            }
            GUI.enabled = true;
        }
```

**Comment by ElmarTalibzade** [comment]
Done! This feature will be included in update 1.1.4
