### ISSUE TITLE
Variable bank editor does not updates when opening another bank

### ISSUE THREAD

**Issue by DmitriyYukhanov** [RockTomate/Issues#6]
**Steps to Reproduce**
* create variables bank 1 with variable A
* create variables bank 2 with variable B
* double click variables bank 1
* double click variables bank 2
* see Variable bank editor still shows variable A from bank 1

**Expected Results**
Updated list of variables from newly opened bank

**Actual Results**
List of variables from previously opened bank

**Comment by ElmarTalibzade** [comment]
Fixed in 1.0.2
