### ISSUE TITLE
Evaluate macroses right from the variables editors

### ISSUE THREAD

**Issue by DmitriyYukhanov** [RockTomate/Issues#9]
**Feature Proposal**
Would be great to somehow evaluate variables values which are made in function mode (fx icon).

**Problem this Solves**
It's often hard to tell if entered value is correct and can evaluate to proper value until it tested in job.
Would be great to be able to quickly check e.g. path("%ProjectDir%\\..\\..\\..\\Folder", true) actual value before running it from job.

**Comment by ElmarTalibzade** [comment]
Unless I misunderstood, you can already do that.
![image](https://user-images.githubusercontent.com/8478519/79220984-f1595800-7e4c-11ea-9b01-0641390ee62c.png)

**Comment by ElmarTalibzade** [comment]
Oh, you mean being able to resolve values on the spot?

**Comment by DmitriyYukhanov** [comment]
Yes I mean see the final value while I'm editing it, perhaps some context menu command which prints result or one more column with resolved value would help here

**Comment by ElmarTalibzade** [comment]
Ah, that's doable. I will add it to 1.0.3 milestone.

**Comment by DmitriyYukhanov** [comment]
Great, thank you!

**Comment by ElmarTalibzade** [comment]
Implemented in 1.0.3
